### ISSUE TITLE
Sinn von L(-b.fhor to -b.fhor) ?

### ISSUE THREAD

**Issue by schreibe** [atecon/FEP#8]
Hi Artur, in der doGWtest-Funktion werden für den bedingten (conditional) Test verzögerte Verlustdifferenziale hinzugefügt. Das ist soweit schön und gut. Aber da steht: 
z += L(-b.fhor to -b.fhor), 
und das sieht etwas komisch aus. Warum nicht einfach L(-b.fhor) ? Oder soll es eigentlich heißen L(-1 to -b.fhor), wäre für den Multistep-Ansatz auch gut denkbar. (Es ist m.E. nicht zwingend, weil man in der Wahl der Bedingungsmenge etwas frei ist bei GW.) Oder sollte diese Syntax irgendeinen gretl-Bug umschiffen? 
Bitte um sachdienliche Hinweise! Danke.

**Comment by schreibe** [comment]
OK, den Part L(-1 to -b.fhor) nehme ich zurück, das wäre inhaltlich nicht korrekt... Bleibt also nur die Frage, warum diese umständliche Syntax gewählt wurde.

**Comment by schreibe** [comment]
Hi Artur, kann ich ein "ping" zu dieser Frage machen? Siehst Du es auch so, dass man statt L(-b.fhor to -b.fhor) einfach L(-b.fhor) schreiben könnte, oder steckt da ein Trick dahinter?

**Comment by schreibe** [comment]
No, I think -b.fhor to -b.fhor is correct, and -1 to -b.fhor would be wrong. For example, take h=b.fhor=3: In a certain period tau you cannot know the realizations tau+1 to tau+3 (=tau+h). So for this test, looking back from the forecast target period tau+h, you must not include the values tau+3-1, tau+3-2. Only tau+3-3=tau (and earlier) can reasonably be included. 
So I don't think it's a bug, just odd syntax.

**Comment by atecon** [comment]
Ah, I see what you mean. Indeed, that sounds reasonable. So, it actually should be:
~~~
h_inst += L(-b.fhor)
~~~

**Comment by schreibe** [comment]
Yes, that's what I mean. I believe it could also make sense to allow:
scalar reachback = -b.fhor - morelags
h_inst += L(-b.fhor to reachback)
, where morelags would be a new scalar (and non-negative) user choice. But that would be an extension, an additional feature - I'm not saying that we need this now.

**Comment by atecon** [comment]
Yes, that would be possible. 
Ok, let's fix that issue. However, I won't be able to do this before Monday but I put it on my TODO list.

**Comment by atecon** [comment]
Pull request is out now:
https://github.com/atecon/FEP/pull/20

**Comment by atecon** [comment]
This issue was solved and got merged into master. I close it now.
